#!/usr/bin/env ruby

unless File.exist?('./Rakefile') || File.exist?('./Gemfile')
  abort 'Please run scopedog from the root of the project.'
end

require 'bundler'
Bundler.require

require "scopedog/cli"

Scopedog::CLI.start(ARGV)
